services:
    frontend:
        build:
            context: Frontend
            dockerfile: ../Dockerfiles/frontend.Dockerfile
        image: frontend
        container_name: frontend
        ports:
            - "3000:80"
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - REACT_APP_API_URL=${REACT_APP_API_URL}
        depends_on:
            - backend

    backend:
        build:
            context: Backend
            dockerfile: ../Dockerfiles/backend.Dockerfile
        image: backend
        container_name: backend
        ports:
            - "8000:8000"
        restart: unless-stopped
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - INSTANCE_CONNECTION_NAME=${INSTANCE_CONNECTION_NAME}
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./Nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - backend
volumes:
    db-data:
    redis_data:
