apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3  # 副本數量，指定3個Pod
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/<project-id>/backend:latest  # 替換成你的映像檔名稱
        ports:
        - containerPort: 8000
