apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # Backend Container
        - name: backend
          image: asia-east1-docker.pkg.dev/vivid-reality-443509-d4/backend-repo/backend:latest
          ports:
            - containerPort: 8000
          env:
            # Cloud SQL 配置
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: 127.0.0.1
            - name: INSTANCE_CONNECTION_NAME
              value: vivid-reality-443509-d4:us-central1:postgres
          volumeMounts:
            - name: cloudsql-proxy-socket
              mountPath: /cloudsql
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "2"

        # Cloud SQL Proxy Container
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.7
          command: ["/cloud_sql_proxy"]
          args: 
            - "--instances=vivid-reality-443509-d4:us-central1:postgres=tcp:5432"
            - "--credential_file=/secrets/service-account.json"
          volumeMounts:
            - name: cloudsql-proxy-socket
              mountPath: /cloudsql
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true

      volumes:
        - name: cloudsql-proxy-socket
          emptyDir: {}
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
